app/urls.py
from django.urls import path

from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.edit, name='add'),
    path('chat/', views.chat, name='chat'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('detail/<int:id>/', views.detail, name='detail'),
    path('delete/<int:id>/', views.delete, name='delete'),
    
]

name/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('app/',include('app.urls')),
    path('admin/', admin.site.urls),

]

app/models.py
from cgitb import text
from django.db import models

class Question(models.Model):
    name = models.CharField('Nom',max_length=200)
    text = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.text


class Member(models.Model):
	name = models.CharField('Nom complet', max_length=255)
	email = models.CharField('E-Mail', max_length=255)
	age = models.IntegerField('âge', blank=True, default=0)

	def __str__(self):
		return self.name

class Product(models.Model):
    name = models.CharField('Nom',max_length=255)
    description = models.CharField('Description',max_length=255)
    prix = models.CharField('prix',max_length=20)
    stock = models.IntegerField('stock',blank=True, default=0)
    image = models.CharField('image',blank=True,max_length=255)
    
    def __str__(self) -> str:
        return self.name

# Create your models here.

app/forms.py
from dataclasses import fields
from pyexpat import model
from django.forms import ModelForm
from app.models import Member, Product


class MemberForm(ModelForm):
	class Meta:
		model = Member
		fields = ('name','email','age',)
        
class ProductForm(ModelForm):
	class Meta:
		model = Product
		fields = ('name','description','prix','stock','image')

class ProductUpdateForm(ModelForm):
    class Meta:
        model = Product
        fields = ('stock',)

app/views.py
from itertools import product
from django.shortcuts import render
from django.http import HttpResponse,response,Http404,HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from .models import Member, Product
from django.utils import timezone
from app.forms import MemberForm,ProductForm,ProductUpdateForm

# def index(request):
#     Question = Question.objects.all().order_by('id')
#     return render(request,'app/index.html',{'Questions':Question})

# Create your views here.


from django.views.generic import ListView #ajouter à


#liste
def index(request):
    products = Product.objects.all().order_by('id') #Obtenez de la valeur
    return render(request, 'app/index.html', {'products':products}) #Passer une valeur au modèle
    
#Liste (ajoutée pour la nation de la page)
class MemberList(ListView):
	model = Member #Modèle à utiliser
	context_object_name='products' #Paramètre de nom d'objet (la valeur par défaut est object_Ça devient une liste)
	template_name='app/index.html' #Spécifier une page de modèle
	paginate_by = 1 #Nombre de pages par page
    
#Nouveau et modifier
def edit(request, id=None):

	if id: #Lorsqu'il y a un identifiant (lors de l'édition)
		#Rechercher par identifiant et renvoyer les résultats ou erreur 404
		product = get_object_or_404(Product, pk=id)
	else: #Quand il n'y a pas d'identifiant (quand neuf)
		#Créer un membre
		product = Product()

	#Au POST (lorsque le bouton d'enregistrement est enfoncé, que ce soit nouveau ou modifier)
	if request.method == 'POST':
		#Générer un formulaire
		form = ProductForm(request.POST, instance=product)
		if form.is_valid(): #Enregistrer si la validation est OK
			product = form.save(commit=False)
			product.save()
			return redirect('app:index')
	else: #Au moment de GET (générer un formulaire)
		form = ProductForm(instance=product)
	
	#Afficher un nouvel écran / modifier l'écran
	return render(request, 'app/edit.html', dict(form=form, id=id))
#Effacer


#Détails (bonus)
#Détails (bonus)
def detail(request, id):
    product = get_object_or_404(Product, pk=id)
    print(product.stock)
    form = ProductUpdateForm(instance=product)
    if request.method == 'POST':
        form = ProductUpdateForm(request.POST, instance=product)
        if form.is_valid(): #Enregistrer si la validation est OK
            form.save()
            print(form)
            return redirect('app:index')
    # form = ProductUpdateForm(instance=product)
    return render(request, 'app/detail.html',{'product':product,'form': form})



def delete(request, id):
	# return HttpResponse("Effacer")
	member = get_object_or_404(Member, pk=id)
	member.delete()
	return redirect('app:index')

def chat(request):
    #member = get_object_or_404(Member, pk=id)
    return render(request, 'app/chat.html')

app/templates/app/chat.html
{% load static %}
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet"  href="{%  static  'css/style.css'  %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">
{% block content %}

<nav>
    <div>
        <a href="{% url 'app:index' %}">
            <img width=80px src="https://ml1zg2et1ufr.i.optimole.com/p72I_n0-GVuFnXmX/w:1200/h:299/q:94/https://royal.cheerz.com/wp-content/uploads/2021/06/LOGO-CHEERZ-BLEU.png" alt="">
        </a>
    </div>
    <ul >
       
    </ul>
    <a href="">mon compte</a>

</nav>

<div class="message">
    <div id="screen">
        <div id="header">CHATBOT</div>
        <div id="messageDisplaySection">
            <div id="messages">
            </div>
            <!-- bot messages -->
            <!-- <div class="chat botMessages">Bonjour, comment puis-je vous aider ?</div> -->

            <!-- usersMessages -->
            <!-- <div id="messagesContainer">
            <div class="chat usersMessages">J’ai besoin de votre aide pour construire un site web.</div>
        </div> -->
    </div>
        <!-- messages input field -->
        <div id="userInput">
        <form>
            <input type="text" class="messages" id="message" name="message" placeholder="Message">
            <input type="submit" id="send" value="Send">
        </form>
        </div>
    </div>
</div>


  

  <script type="text/javascript">
    let url = `ws://${window.location.host}/ws/socket-server/`

    const chatSocket = new WebSocket(url)

    chatSocket.onmessage = function(e){
        let data = JSON.parse(e.data)
        console.log('Data:', data)
        if (data.type = 'chat') {
          let messages = document.getElementById('messages')
          messages.insertAdjacentHTML('beforeend', `<div><p>${data.message}</p></div>`)
        }
    }

    let form = document.querySelector('form')
    form.addEventListener('submit', function(e){
        e.preventDefault()
        let message = e.target.message.value
        chatSocket.send(JSON.stringify({
            message
        }))
    })
  </script>

<a href="{% url 'app:index' %}" class="btn btn-default btn-sm" style="margin-left:20px;">Revenir</a>

{% endblock content %}

<!--Insérer js-->
{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<script src="https://kit.fontawesome.com/811878f6ff.js" crossorigin="anonymous"></script>
{% endblock %}

app/templates/app/detail.html
{% load static %}
<link rel="stylesheet"  href="{%  static  'css/style.css'  %}">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet"  href="{%  static  'css/style.css'  %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">
{% block content %}
<div class="chatter"> <a href="{% url 'app:chat' %}"> <i class="fas fa-comment-dots"></i> </a></div>

<nav>
    <div>
        <a href="{% url 'app:index' %}">
            <img width=80px src="https://ml1zg2et1ufr.i.optimole.com/p72I_n0-GVuFnXmX/w:1200/h:299/q:94/https://royal.cheerz.com/wp-content/uploads/2021/06/LOGO-CHEERZ-BLEU.png" alt="">
        </a>
    </div>
    <ul >
        
       
    </ul>
    <a href="">mon compte</a>

</nav>
<section class="section-product">
    <picture>
        <img src="{{ product.image }}" alt="">
    </picture>
    <article>
        <h1>{{product.name}}</h1>
        
        <p>{{product.description}} </p>
        
        <h2>{{product.prix}}</h2>
        <label> </label>
        <a class="button button-action" href="#">{{product.stock}}</a>
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit">
         </form>
    </article>
</section>

<a href="{% url 'app:index' %}" class="btn btn-default btn-sm" style="margin-left:20px;">Revenir</a>
{% endblock content %}

<script src="https://kit.fontawesome.com/811878f6ff.js" crossorigin="anonymous"></script>

app/templates/app/edit.html
{% load static %}
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet"  href="{%  static  'css/style.css'  %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">

<nav>
    <div>
        <a href="{% url 'app:index' %}">
            <img width=80px src="https://ml1zg2et1ufr.i.optimole.com/p72I_n0-GVuFnXmX/w:1200/h:299/q:94/https://royal.cheerz.com/wp-content/uploads/2021/06/LOGO-CHEERZ-BLEU.png" alt="">
        </a>
    </div>
    <ul >
       
         
       
    </ul>
    <a href="">mon compte</a>

</nav>
{% block content %}
<div class="form">
    <h3 class="page-header">Ajouter un produit</h3>
    <form action="{% url 'app:add' %}" method="post" class="form-horizontal" role="form">
      {% csrf_token %}
      {{ form  }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">Envoyer</button>
        </div>
      </div>
    </form>
  </div>
    <a href="{% url 'app:index' %}" class="btn btn-default btn-sm" style="margin-left:20px;">Revenir</a>
{% endblock content %}

app/templates/app/index.html
{% load static %}
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet"  href="{%  static  'css/style.css'  %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">
{% block content %}
<div class="chatter"> <a href="{% url 'app:chat' %}"> <i class="fas fa-comment-dots"></i></a></div>
<div class="navup">
    <p>Le 6 mars c'est la fête des mamies ! Pensez à une petite carte cadeau pour lui faire plaisir 💛| Voir +</p>
</div>
<nav>
    <div>
        <a href="{% url 'app:index' %}">
            <img width=80px src="https://ml1zg2et1ufr.i.optimole.com/p72I_n0-GVuFnXmX/w:1200/h:299/q:94/https://royal.cheerz.com/wp-content/uploads/2021/06/LOGO-CHEERZ-BLEU.png" alt="">
        </a>
    </div>
    <ul >
        <li >Albums photo</li>
        <li >Cadre photo</li>
        <li>Calendrier photo</li>
        <li>Box photo </li>
        <li>Fête des mères </li> 
       
    </ul>
    <a href="">mon compte</a>

</nav>


        
        <section  class="section-collection">
            {% for product in products %}
            {% if product.stock > 0 %}
          
            <div class="collection">
                <picture>
                    <img src="{{ product.image }}" alt="">
                </picture>
                <div>
                    <h3>
                        {{ product.name }}
                    </h3>
                    <a href="{% url 'app:detail' id=product.id %}"><i id="arrow" class="fas fa-arrow-right"></i></a>
                </div>
            </div>
            {% endif %}

            {% endfor %}
            
        
        </section>
        <div class="add">
            <h3>Ajouter un produit</h3>
            <a href="{% url 'app:add' %}"> <i class="far fa-plus-square"></i> </a>
        </div>
<!--Mettez la page ici-->

{% endblock content %}

<!--Insérer js-->
{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<script src="https://kit.fontawesome.com/811878f6ff.js" crossorigin="anonymous"></script>
{% endblock %}